package vegalite

// generated by https://mholt.github.io/json-to-go/ , then modified by hand

type JSON struct {
	Schema      string   `json:"$schema"`
	Description string   `json:"description"`
	Data        Data     `json:"data"`
	Mark        Mark     `json:"mark"`
	Height      string   `json:"height"`
	Width       string   `json:"width"`
	Encoding    Encoding `json:"encoding"`
	Title       Title    `json:"title"`
	Params      []Params `json:"params"`
}
type Format struct {
	Type string `json:"type"`
}
type Data struct {
	Values string `json:"values"`
	Format Format `json:"format"`
}
type Mark struct {
	Type    string `json:"type"`
	Tooltip bool   `json:"tooltip"`
	Point   bool   `json:"point"`
	Size    int    `json:"size,omitempty"`
}
type Scale struct {
	Type string `json:"type"`
}
type XY struct {
	Field    string `json:"field"`
	Type     string `json:"type,omitempty"`
	TimeUnit string `json:"timeUnit,omitempty"`
	Scale    *Scale `json:"scale,omitempty"`
}
type Color struct {
	Field string `json:"field"`
	Type  string `json:"type"`
}
type Condition struct {
	Param string `json:"param"`
	Value int    `json:"value"`
}
type Opacity struct {
	Condition Condition `json:"condition"`
	Value     float64   `json:"value"`
}
type Encoding struct {
	X       XY       `json:"x"`
	Y       XY       `json:"y"`
	Color   Color    `json:"color"`
	Opacity Opacity  `json:"opacity"`
	XOffset *XOffset `json:"xOffset,omitempty"`
}
type Title struct {
	Text string `json:"text"`
}
type Select struct {
	Type   string   `json:"type"`
	Fields []string `json:"fields"`
}
type Params struct {
	Name   string `json:"name"`
	Bind   string `json:"bind"`
	Select Select `json:"select"`
}

type XOffset struct {
	Field string `json:"field"`
}
